FROM  oven/bun:1

WORKDIR /usr/src/app

COPY ./packages  ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./apps/backend  ./apps/backend 


RUN bun install 
RUN bun run db:generate

EXPOSE 8080

CMD [ "bun","start","start:backend" ]


